#!/usr/bin/env bash

cd "$(dirname "$0")/../.."   # run from the umbrella root

# the archive goes out as the version that CMakeLists.txt downloads, which
# new data have to raise first [see DATA_VERSION there]
bash upload-to-package-registry BinaryKnapsackBlock/data/txt.tgz \
     "$(sed -n 's/^set(DATA_VERSION \(.*\))$/\1/p' BinaryKnapsackBlock/CMakeLists.txt)"
